sudo: required

language: python

services:
  - docker

# Setup build matrix
env:
  - RCD_ARCH=x86
  - RCD_ARCH=armv7

before_install:

  script:
    # Setup armv7 docker cross-compiler
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker-compose -f builder-compose.yml build

deploy:
  skip_cleanup: true

  script:
    # Login to docker for push
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    # Push artifacts to repo
    - docker push derekmerck/rcdiana:${RCD_ARCH}_conda
    - docker push derekmerck/rcdiana:${RCD_ARCH}_orthanc
