sudo: required

language: python

services:
  - docker

# Setup build matrix
env:
  - RCD_ARCH=amd64
  - RCD_ARCH=armv7hf

before_install:

  # Setup armv7 docker cross-compiler
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker-compose -f builder-compose.yml build

  # Login to docker for push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Push artifacts to repo
  - docker tag "rcdiana:${RCD_ARCH}_conda" "$DOCKER_USERNAME/rcdiana:${RCD_ARCH}_conda"
  - docker push "$DOCKER_USERNAME/rcdiana:${RCD_ARCH}_conda"

  - docker tag "rcdiana:${RCD_ARCH}_orthanc" "$DOCKER_USERNAME/rcdiana:${RCD_ARCH}_orthanc"
  - docker push "$DOCKER_USERNAME/rcdiana:${RCD_ARCH}_orthanc"
