sudo: required

language: python

services:
  - docker

# Setup build matrix
env:
#  - RCD_ARCH=aarch64  # Jetson TX2

  - RCD_ARCH=amd64 RCD_TARGET=conda
  - RCD_ARCH=amd64 RCD_TARGET=orthan
  - RCD_ARCH=amd64 RCD_TARGET=opencv

#  - RCD_ARCH=armv7hf  # Raspberry Pi 3

script:

  # Setup armv7 docker cross-compiler
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker-compose -f builder-compose.yml build $RCD_TARGET

  # Login to docker for push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Push artifacts to repo
  - docker tag "rcdiana:${RCD_ARCH}_${RCD_TARGET}" "$DOCKER_USERNAME/rcdiana:${RCD_ARCH}_${RCD_TARGET}"
  - docker push "$DOCKER_USERNAME/rcdiana:${RCD_ARCH}_${RCD_TARGET}"
