sudo: required

language: python

services:
  - docker

before_install:

  # Setup armv7 docker cross-compiler
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - export RCD_ARCH=armv7
  - docker-compose -f builder-compose.yml build
  - docker push derekmerck/rcdiana:${RCD_ARCH}_conda
  - docker push derekmerck/rcdiana:${RCD_ARCH}_orthanc

  - export RCD_ARCH=x86
  - docker-compose -f builder-compose.yml build
  - docker push derekmerck/rcdiana:${RCD_ARCH}_conda
  - docker push derekmerck/rcdiana:${RCD_ARCH}_orthanc
