sudo: required

language: python

services:
  - docker

before_install:
  - docker-compose -f builder-compose.yml build

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker login

  - docker push derekmerck/rcdiana:armv7_conda
  - docker push derekmerck/rcdiana:armv7_orthanc
