# Multi-architecture builder for rcdiana:conda and rcdiana:orthanc

# set your env: $ export RCD_ARCH=amd64 / armv7hf / aarch64
version: '2.2'

services:
  base:
    build:
      context: base
      dockerfile: ${RCD_ARCH}/Dockerfile
      args:
        - RCD_ARCH  # Pass env into Dockerfile for substition
    image: base
#    privileged: True
    command: "/bin/bash"  # Exit immediately

  # Can skip ssh in final build if useful by depending conda and orthanc directly on base
  sshd:
    build: ./sshd
    image: sshd
    depends_on:
      - base
#    privileged: True
    command: "/bin/bash"  # Exit immediately

  conda:
    build: ./conda
    image: rcdiana:${RCD_ARCH}_conda
    depends_on:
      - sshd
    init: true
    restart: always
    privileged: true
    ports:
      - "322:22"

#   volumes:
#     - 'diana-data:/usr/src/app'


# Can further derive from conda for specific services (diana-mon)
  orthanc:
    build: ./orthanc
    image: rcdiana:${RCD_ARCH}_orthanc
    depends_on:
      - sshd
    init: true
    restart: always
    privileged: True
    ports:
      - "4080:8042"
      - "4242:4242"
      - "422:22"

  opencv:
    build:
      context: ./opencv
      args:
        - RCD_ARCH
    image: rcdiana:${RCD_ARCH}_opencv
#    depends_on:
#      - conda    init: true
    restart: always
    privileged: true

#   volumes:
#     - 'diana-data:/var/lib/orthanc/db'


# Can further derive from orthanc for specific services (autorouting)

