# Project builder for resin.io devices
# Configure with image tags for appropirate architectures

version: 2.1

services:

  orthanc:
    image: derekmerck/orthanc:armv7_orthanc
#    init: true
    restart: always
    privileged: true
    ports:
      - "422:22"
      - "4242:4242"
      - "8042:8042"

  conda:
    image: derekmerck/conda:armv7_conda
#    init: true
    restart: always
    privileged: true
    ports:
      - "322:22"

