# Project builder for resin.io devices
# Configure with image tags for appropriate architectures
# Note, resin does not have a way to set RCD_ARCH, so set it manually

version: '2.1'

services:

  orthanc:
    image: derekmerck/rcdiana:${RCD_ARCH}_orthanc
#    init: true
    restart: always
    privileged: true
    ports:
      - "422:22"
      - "4242:4242"
      - "8042:8042"

  conda:
    image: derekmerck/rcdiana:${RCD_ARCH}_conda
#    init: true
    restart: always
    privileged: true
    ports:
      - "522:22"

  keras:
    image: derekmerck/rcdiana:${RCD_ARCH}_keras
#    init: true
    restart: always
    privileged: true
    ports:
      - "622:22"