#!/bin/sh

WHERE_OPENCV=/opt/opencv/opencv
WHERE_OPENCV_CONTRIB=/opt/opencv/opencv_contrib

cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D PYTHON2_EXECUTABLE=/opt/conda/bin/python \
	-D INSTALL_PYTHON_EXAMPLES=ON \
	-D OPENCV_EXTRA_MODULES_PATH=$WHERE_OPENCV_CONTRIB/modules \
	-D BUILD_EXAMPLES=ON $WHERE_OPENCV